version: "3"

volumes:
  ShrimpStatic:
    external: true
  ShrimpDB:
    external: true
  shrimpcache:
    external: true

services:
  shrimpbot:
    restart: unless-stopped
    build: ./src
    volumes:
      - ShrimpStatic:/static
    container_name: shrimpBot
    ports:
      - 8114:8114

  shrimppostgres:
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=shrimpbot
      - POSTGRES_PASSWORD=337823521
      - POSTGRES_DB=shrimpdb
    volumes:
      - ./schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - ShrimpDB:/var/lib/postgresql/data
    container_name: shrimpDB
    
  shrimpcache:
    restart: unless-stopped
    image: redis:7.2.1-alpine
    command: redis-server --loglevel warning
    volumes:
      - shrimpcache:/data
    container_name: shrimpCache